apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: gke-devops-app
build:
  artifacts:
    - image: gke-devops-app
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml

deploy:
  kubectl: {}

# --- ADD THIS SECTION ---
profiles:
  - name: staging
    deploy:
      kubectl: {}

  - name: prod
    deploy:
      kubectl: {}
